build:
  environment:
    php:
      version: '8.1'
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
          - command: phpcs-run --config phpcs.xml
checks:
    php: true
